baseURL = 'https://www.drmarkpowell.com/'
paginate = 5
languageCode = 'en-us'
title = 'Mark Powell'
theme = 'PaperMod'
publishDir = 'public'

[markup.goldmark.renderer]
    unsafe = true

[params]
    mainSections = ["posts"]
    ShowFullTextinRSS = true
    ShowCodeCopyButtons = true
    ShowPostNavLinks = true
    customCss = ["css/extra.css"]

    [profileMode]
    enabled = false

    [params.homeInfoParams]
    Title = "Mostly Mobile Musings"
    Content = "Methodically Making Magic on My Mac"

    [[params.socialIcons]]
    name = "Mastodon"
    url = "https://iosdev.space/@drmarkpowell"

    [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/drmarkpowell"

    [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/drmarkpowell"

    [[params.socialIcons]]
    name = "Email"
    url = "mailto:drmarkpowell@gmail.com"

[menu]
    [[menu.main]]
    identifier = 'Blog'
    name = 'Blog'
    url = '/posts/'

    [[menu.main]]
    identifier = 'apps'
    name = 'Apps'
    url = '/apps/apps/'